### ISSUE TITLE
No heart texture.

### ISSUE THREAD

**Issue by MrJetLag** [sdphantomz3/lifestealmod#3]
When I withdraw hearts, they appear as nether stars. I've tried reinstalling but it still appears as a nether star.

**Comment by sdphantomz3** [comment]
This is because in the latest update, I made the mod server side only. And that's why the heart appears as a nether star. If you want the heart texture, you can download the 1.2.0 version, which has a custom heart item with a texture, but that version of the mod is required on both the server and client.

**1.2.0:** https://modrinth.com/mod/lifesteal-smp/version/1.2.0

**Comment by sdphantomz3** [comment]
I am also working on a resource pack for this mod for the heart texture, if you don't want to download the older version. The resource pack will take a while to release, though.
